declare function $(_:any): JQuery;

declare class Lobby {
    // $battleRoyalRuleModal: r;
    // $lastManRuleModal: r;
    // $rankedRuleModal: r;
    // $roomId: r;
    // $roomName: r;
    // $ruleButton: r;
    // $shuffleTeamButton: r;
    // $view: r;
    ANSWERING_MODES: Object;
    RULE_DESCRIPED_GAME_MODES: Array;
    _avatarChangeListener: Listener;
    _forceSpectatorListner: Listener;
    _gameClosedListner: Listener;
    _gameStartListner: Listener;
    _hostPromotionListner: Listener;
    _joinTeamListener: Listener;
    _nameChangeListner: Listener;
    _newPlayerListner: Listener;
    _playerAnswerModeChangeListener: Listener;
    _playerLeaveListner: Listener;
    _readyChangeListner: Listener;
    _settingListener: Listener;
    _shuffleTeamsListener: Listener;
    _spectatorChangeToPlayer: Listener;
    _spectatorLeftListener: Listener;
    _spectatorNameChangeListner: Listener;
    addPlayer: function;
    canJoin: any;
    changeGameSettings: function;
    changeToSpectator: function;
    checkAutoDisplayRuleModal: function;
    closeView: function;
    constructor() ;
    fireMainButtonEvent: function;
    getPlayerByName: function;
    inLobby: boolean;
    inputModeSelector: LobbyInputModeSelector;
    isHost: any;
    joinBlockedMessage: any;
    kickPlayer: function;
    leave: function;
    lobbyAvatarContainer: LobbyAvatarContainer;
    mainButton: LobbyMainButton;
    numberOfPlayers: any;
    numberOfPlayersReady: any;
    openView: function;
    ownGamePlayerId: null;
    playerCounter: LobbyPlayerCounter;
    players: Object;
    promoteHost: function;
    removePlayer: function;
    ruleModal: LobbyRuleModal;
    setNewHost: function;
    setPlayerTeam: function;
    setupLobby: function;
    showRules: function;
    shuffleTeams: function;
    soloMode: boolean;
    toggleRuleButton: function;
    updateMainButton: function;
    updatePlayerCounter: function;
    viewSettings: function;
}

declare class Quiz {

    // $inputContainer: r;
    // $nexusTargetLayer: r;
    // $startReturnToLobbyButton: r;
    // $videoOverflowContainer: r;
    // $view: r;
    CURRENT_BUFFER_FOCUS_PHASES: Array;
    NEXUS_DELAYED_EVENT_DELAY: number;
    NO_JAM_THEME_DISPlAY_PHASES: Array;
    QUIZ_STATES: Object;
    SCORE_TYPE_IDS: Object;
    SHOW_SELECTION_IDS: Object;
    SHOW_TIMER_PHASES: Array;
    SKIP_PHASES: Array;
    TEAM_ANSWER_IN_CHAT_STATES: Object;
    _bossLifeChangeListener: Listener;
    _bossMultipleChoiceListener: Listener;
    _bossResultListener: Listener;
    _bossSongCountChangeListener: Listener;
    _bossUpdateQueueListener: Listener;
    _endResultListner: Listener;
    _errorListener: Listener;
    _extraGuessTimeListener: Listener;
    _groupSlotMap: Object;
    _guessPhaseOverListner: Listener;
    _guessTimeChangeListener: Listener;
    _jamGameRestartingListener: Listener;
    _jamVoteStartedListener: Listener;
    _lateJoinTriggeredListener: Listener;
    _messageFlagBanListener: Listener;
    _messageFlagWarnedListener: Listener;
    _modMessageFlagListener: Listener;
    _nameChangeListner: Listener;
    _nameHintListener: Listener;
    _newBossListener: Listener;
    _nextVideoInfoListener: Listener;
    _nexusGameEventsListener: Listener;
    _noPlayersListner: Listener;
    _noSongsListner: Listener;
    _pauseTriggerListener: Listener;
    _peekAnswersListener: Listener;
    _playNextSongListner: Listener;
    _playerAnswerListener: Listener;
    _playerAnswerListner: Listener;
    _playerHiddenListener: Listener;
    _playerHintUsedListener: Listener;
    _playerLateJoinListener: Listener;
    _playerLeaveListner: Listener;
    _playerRejoiningListener: Listener;
    _quizOverListner: Listener;
    _quizreadyListner: Listener;
    _removePlayerListener: Listener;
    _resultListner: Listener;
    _returnVoteResultListener: Listener;
    _returnVoteStartListner: Listener;
    _sendFeedbackListner: Listener;
    _skipMessageListener: Listener;
    _skipNextPhaseListener: Listener;
    _skippingVideoListener: Listener;
    _songHintListener: Listener;
    _spectatorLeftListener: Listener;
    _teamMemberAnswerListener: Listener;
    _unpauseTriggerListener: Listener;
    _waitingForBufferingListner: Listener;
    _xpCreditGainListner: Listener;
    addLateJoinPlayer: function;
    amqAwardsOverlay: AmqAwardsOverlay;
    answerInput: QuizAnswerInput;
    avatarAssetHandler: QuizAvatarAssetHandler;
    avatarContainer: QuizAvatarContainer;
    bossModeDisplay: BossModeDisplay;
    clearAbilityTarget: function;
    clearSwapIcons: function;
    closeView: function;
    constructor() ;
    currentAbilityTarget: null;
    displayAbilityTarget: function;
    displayListNumber: function;
    eventQueue: QuizEventQueue;
    flaggedMessageContainer: FlaggedMessageContainer;
    getNexusTarget: function;
    groupSlotMap: any;
    handleAutoHide: function;
    handleNewNexusCharacterClick: function;
    handleNexusEvent: function;
    handleNoEmotePoint: function;
    handlePlayerOnlyChatPoint: function;
    hintController: QuizHintController;
    inQuiz: boolean;
    infoContainer: QuizInfoContainer;
    inputFocused: boolean;
    isHost: boolean;
    jamThemeDisplay: JamThemeDisplay;
    jamVoteController: JamVoteController;
    lateJoinButton: StandardButton;
    leave: function;
    nexusAttackOrderContainer: QuizNexusAttackOrderContainer;
    nexusEventLog: Array;
    onLastSong: boolean;
    openView: function;
    ownGroupSlot: any;
    pauseButton: PauseButton;
    promoteHost: function;
    resetMultipleChoice: boolean;
    returnVoteController: ReturnVoteController;
    scoreboard: QuizScoreboard;
    selectAvatarGroup: function;
    setInputInFocus: function;
    settingUpFirstSong: boolean;
    setup: function;
    setupQuiz: function;
    skipClicked: function;
    skipController: QuizSkipController;
    soloMode: boolean;
    sortNexusEvents: function;
    startReturnLobbyVote: function;
    targetingPlayerId: null;
    updateEnemyTarget: function;
    updateSwapTarget: function;
    videoOverlay: VideoOverlay;
    videoReady: function;
    videoTimerBar: TimerBar;
    viewSettings: function;
}